name: Verify Links
on:
  push:
    branches:
      - main
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Run Tests
        run: go test -v